### ISSUE TITLE
Font Awesome 6 style selection for kit

### ISSUE THREAD

**Issue by sanderpotjer** [verbb/icon-picker#75]
### What are you trying to do?

When loading Font Awesome 6 via a kit, all styles are loaded. Unfortunaltey you can't configure this from within a kit in Font Awesome. It would be great if we can select in the Icon Sets settings of Icon Picker which of the kit styles should be used. 

Currently all styles are loaded, resulting in many "duplicates" and we're only using one style on the frontend.

<img width="839" alt="Schermafbeelding 2023-02-24 om 16 04 29" src="https://user-images.githubusercontent.com/522834/221212121-6db7c886-914e-46a3-bf0b-1ee5bc297b62.png">

### What's your proposed solution?

Adding an option to select/set the styles in the Icon Sets settings. Via the `fetchIcons` the famlilyStyles are loaded, basically you want to be able to select from this options and only load icons of the selected style(s).

**Comment by pascalminator** [comment]
I tought I could bypass this limitation by creating a kit restrained to one specific style only in Font Awesome, but it does not work really well :

![Capture d’écran 2024-03-28 120437](https://github.com/verbb/icon-picker/assets/13754636/d1ce952f-d269-4042-a36d-57d941e3672e)

It still shows the same icon multi time, but with the same style. There is also some icons that just does not show up at all. This feature request is a must and I don't understand why it's being ignored by the devs.

**Comment by engram-design** [comment]
While you can restrict the kits in the Font Awesome settings:

<img width="677" alt="image" src="https://github.com/verbb/icon-picker/assets/1221575/89fb9c16-a290-405b-a379-03efef21da4a">

That's not accessible via the API when fetching the kit, which would what I would expect, and have been waiting on a response from them about this.

Otherwise, we're going to have to add another checkbox in the icon set settings to select your styles. This isn't ideal as it could lead to confusing results (you only enable the "Solid" style in your kit settings, but you try and load "Solid" and "Sharp" in the Icon Picker set settings - you'll only load "Solid" due to the kit restrictions).

Still looking into options.

**Comment by engram-design** [comment]
Just to provide feedback here, the Font Awesome crew say it's not currently possible to limit API responses for a style, so we would need to manage this on our end. We'll probably have to introduce some checkboxes on which styles to include, despite the API pulling them all in. It would be filtering on our end.

It's a bit of double-handling, but there's no other option at the moment.

**Comment by pascalminator** [comment]
I am personally totally fine with your proposition to add checkboxes in the settings. It would prevent end users to select incorrect styles and would fix my problems.

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/icon-picker:"dev-craft-4 as 2.0.17"`.

**Comment by engram-design** [comment]
Added in [2.0.18](https://github.com/verbb/icon-picker/releases/tag/2.0.18)
