### ISSUE TITLE
Using ionicons 7.1

### ISSUE THREAD

**Issue by sjcallender** [verbb/icon-picker#80]
### Question

Since ionicons 7.1 doesn't use a publicly available css file to use for remote loading per the [docs](https://verbb.io/craft-plugins/icon-picker/docs/developers/icon-sets#example)...

***
        // Add the remote CSS to rendering
        $this->fonts[] = [
            'type' => 'remote',
            'name' => 'Ionicons',
            'url' => 'https://unpkg.com/ionicons@4.4.4/dist/css/ionicons.min.css',
        ];
***

... I'm wondering if you have a suggestion for how to use it with the plugin.

I'm also noting ionicons organizes their font styles by "outline," "filled," and "sharp." Not sure if that would complicate font selection in the field too.

Any insights are appreciated!

**Comment by engram-design** [comment]
We do support [Ionicons 5.2.1](https://github.com/verbb/icon-picker/blob/craft-4/src/iconsets/Ionicons.php) natively, but that's because I believe it was the last set that wasn't JS-based. The tedious part is really just the [icon schema](https://github.com/verbb/icon-picker/tree/craft-4/src/json).

Although, since our refactor it should be possible to use them (similar to https://github.com/verbb/icon-picker/blob/craft-4/src/iconsets/Feather.php).

As for separate styles, that'll be fine - probably just separate icon sets.

**Comment by sjcallender** [comment]
Ah, I forgot to mention, we're still on Craft 3. We're prepping for Craft 4, but this site currently uses dolphiq's iconpicker plugin. We need to replace it in Craft 3 first, then we can update to Craft 4. But maybe we just hold off and move to your plugin when we update to Craft 4 since this plugin has more built-in in the Craft 4 version. Is that what you would suggest?

**Comment by engram-design** [comment]
I think that would probably be a good option! We refactored all the icon set logic for Craft 4, and won’t be backporting all that new support for more “advanced” icon sets like this.

**Comment by sjcallender** [comment]
Okay. That makes sense. We'll just migrate after we update to Craft 4. I'll close this and if we run into issues, will just reach out again. Thanks!
