### ISSUE TITLE
Dont inline SVG´s when not Sprite

### ISSUE THREAD

**Issue by Metis77** [verbb/icon-picker#95]
### What are you trying to do?

When inlining SVGs they overwrite each others CSS Styles, whenever using same CSS Classes.
This results in wrong display of those icons.

### What's your proposed solution?

Whenever SVGs are used directly (no sprites) they should not be inlined, but uses with an HTML <img> tag.
This scopes the css styles to each SVG Image and prevents that error.

**Comment by engram-design** [comment]
That'd be due to inline CSS styles included in your SVG's, is that correct? 

If so, then yes - you'd get collisions of styles. It's highly recommended to not include inline `<style>` content in your SVGs if you can help it, or at least properly name them to have unique IDs or classes that styles are tied to.

We inline SVGs for performance. If we needed to perform a network request for each icon (which could be in the thousands) that would be problematic. I tested at the time the difference between the two approaches, and it was very noticeable.

**Comment by Metis77** [comment]
Ok, I understand the priority for performance.
Thanks for getting back so quickly.
